name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Zip build folder
        run: |
          cd dist
          zip -r ../csanalyzer-extension.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: csanalyzer-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
